package ecologylab.semantics.metadata.builtins;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2012) Interface Ecology Lab.
 */

import ecologylab.semantics.metadata.builtins.CompoundDocument;
import ecologylab.semantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.semantics.metametadata.MetaMetadataCompositeField;
import ecologylab.semantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_inherit;
import java.util.List;
import java.util.Map;

/** 
 *The PDF class.
 */ 
@simpl_inherit
public class Pdf extends CompoundDocument
{
	public Pdf()
	{ super(); }

	public Pdf(MetaMetadataCompositeField mmd) {
		super(mmd);
	}

}
