package ecologylab.bigsemantics.metadata.builtins.person.author;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2016) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.person.author.Author;
import ecologylab.bigsemantics.metadata.builtins.person.author.TedauthorQuote;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metadata.scalar.MetadataString;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_collection;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.String;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class TedAuthor extends Author
{
	@simpl_scalar
	private MetadataString occupation;

	@simpl_scalar
	private MetadataString firstP;

	@simpl_scalar
	private MetadataString secondP;

	@simpl_scalar
	private MetadataString credentials;

	@simpl_scalar
	private MetadataString whatOthersSay;

	@simpl_collection("badge")
	@mm_name("badges")
	private List<MetadataString> badges;

	@simpl_collection("tedauthor_quote")
	@mm_name("quotes")
	private List<TedauthorQuote> quotes;

	public TedAuthor()
	{ super(); }

	public TedAuthor(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataString	occupation()
	{
		MetadataString	result = this.occupation;
		if (result == null)
		{
			result = new MetadataString();
			this.occupation = result;
		}
		return result;
	}

	public String getOccupation()
	{
		return this.occupation == null ? null : occupation().getValue();
	}

	public MetadataString getOccupationMetadata()
	{
		return occupation;
	}

	public void setOccupation(String occupation)
	{
		if (occupation != null)
			this.occupation().setValue(occupation);
	}

	public void setOccupationMetadata(MetadataString occupation)
	{
		this.occupation = occupation;
	}

	public MetadataString	firstP()
	{
		MetadataString	result = this.firstP;
		if (result == null)
		{
			result = new MetadataString();
			this.firstP = result;
		}
		return result;
	}

	public String getFirstP()
	{
		return this.firstP == null ? null : firstP().getValue();
	}

	public MetadataString getFirstPMetadata()
	{
		return firstP;
	}

	public void setFirstP(String firstP)
	{
		if (firstP != null)
			this.firstP().setValue(firstP);
	}

	public void setFirstPMetadata(MetadataString firstP)
	{
		this.firstP = firstP;
	}

	public MetadataString	secondP()
	{
		MetadataString	result = this.secondP;
		if (result == null)
		{
			result = new MetadataString();
			this.secondP = result;
		}
		return result;
	}

	public String getSecondP()
	{
		return this.secondP == null ? null : secondP().getValue();
	}

	public MetadataString getSecondPMetadata()
	{
		return secondP;
	}

	public void setSecondP(String secondP)
	{
		if (secondP != null)
			this.secondP().setValue(secondP);
	}

	public void setSecondPMetadata(MetadataString secondP)
	{
		this.secondP = secondP;
	}

	public MetadataString	credentials()
	{
		MetadataString	result = this.credentials;
		if (result == null)
		{
			result = new MetadataString();
			this.credentials = result;
		}
		return result;
	}

	public String getCredentials()
	{
		return this.credentials == null ? null : credentials().getValue();
	}

	public MetadataString getCredentialsMetadata()
	{
		return credentials;
	}

	public void setCredentials(String credentials)
	{
		if (credentials != null)
			this.credentials().setValue(credentials);
	}

	public void setCredentialsMetadata(MetadataString credentials)
	{
		this.credentials = credentials;
	}

	public MetadataString	whatOthersSay()
	{
		MetadataString	result = this.whatOthersSay;
		if (result == null)
		{
			result = new MetadataString();
			this.whatOthersSay = result;
		}
		return result;
	}

	public String getWhatOthersSay()
	{
		return this.whatOthersSay == null ? null : whatOthersSay().getValue();
	}

	public MetadataString getWhatOthersSayMetadata()
	{
		return whatOthersSay;
	}

	public void setWhatOthersSay(String whatOthersSay)
	{
		if (whatOthersSay != null)
			this.whatOthersSay().setValue(whatOthersSay);
	}

	public void setWhatOthersSayMetadata(MetadataString whatOthersSay)
	{
		this.whatOthersSay = whatOthersSay;
	}

	public List<MetadataString> getBadges()
	{
		return badges;
	}

  // lazy evaluation:
  public List<MetadataString> badges()
  {
    if (badges == null)
      badges = new ArrayList<MetadataString>();
    return badges;
  }

  // addTo:
  public void addToBadges(MetadataString element)
  {
    badges().add(element);
  }

  // size:
  public int badgesSize()
  {
    return badges == null ? 0 : badges.size();
  }

	public void setBadges(List<MetadataString> badges)
	{
		this.badges = badges;
	}

	public List<TedauthorQuote> getQuotes()
	{
		return quotes;
	}

  // lazy evaluation:
  public List<TedauthorQuote> quotes()
  {
    if (quotes == null)
      quotes = new ArrayList<TedauthorQuote>();
    return quotes;
  }

  // addTo:
  public void addToQuotes(TedauthorQuote element)
  {
    quotes().add(element);
  }

  // size:
  public int quotesSize()
  {
    return quotes == null ? 0 : quotes.size();
  }

	public void setQuotes(List<TedauthorQuote> quotes)
	{
		this.quotes = quotes;
	}
}
