package ecologylab.bigsemantics.metadata.builtins.person.author;

/**
 * Automatically generated by MetaMetadataJavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2015) Interface Ecology Lab.
 */

import ecologylab.bigsemantics.generated.library.creativeWork.TedtalkVideo;
import ecologylab.bigsemantics.metadata.builtins.MetadataBuiltinsTypesScope;
import ecologylab.bigsemantics.metadata.builtins.RichDocument;
import ecologylab.bigsemantics.metadata.mm_name;
import ecologylab.bigsemantics.metadata.scalar.MetadataString;
import ecologylab.bigsemantics.metametadata.MetaMetadataCompositeField;
import ecologylab.bigsemantics.namesandnums.SemanticsNames;
import ecologylab.serialization.annotations.simpl_composite;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.String;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class TedauthorQuote extends RichDocument
{
	@simpl_scalar
	private MetadataString quote;

	@simpl_composite
	@mm_name("ted_talk")
	private TedtalkVideo tedTalk;

	public TedauthorQuote()
	{ super(); }

	public TedauthorQuote(MetaMetadataCompositeField mmd) {
		super(mmd);
	}


	public MetadataString	quote()
	{
		MetadataString	result = this.quote;
		if (result == null)
		{
			result = new MetadataString();
			this.quote = result;
		}
		return result;
	}

	public String getQuote()
	{
		return this.quote == null ? null : quote().getValue();
	}

	public MetadataString getQuoteMetadata()
	{
		return quote;
	}

	public void setQuote(String quote)
	{
		if (quote != null)
			this.quote().setValue(quote);
	}

	public void setQuoteMetadata(MetadataString quote)
	{
		this.quote = quote;
	}

	public TedtalkVideo getTedTalk()
	{
		return tedTalk;
	}

	public void setTedTalk(TedtalkVideo tedTalk)
	{
		this.tedTalk = tedTalk;
	}
}
