//
// TedauthorQuote.cs
// s.im.pl serialization
//
// Generated by MetaMetadataDotNetTranslator.
// Copyright 2017 Interface Ecology Lab. 
//


using Ecologylab.BigSemantics.Generated.Library.CreativeWorkNS;
using Ecologylab.BigSemantics.MetaMetadataNS;
using Ecologylab.BigSemantics.MetadataNS;
using Ecologylab.BigSemantics.MetadataNS.Builtins;
using Ecologylab.BigSemantics.MetadataNS.Scalar;
using Ecologylab.Collections;
using Simpl.Fundamental.Generic;
using Simpl.Serialization;
using Simpl.Serialization.Attributes;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Ecologylab.BigSemantics.MetadataNS.Builtins.PersonNS.AuthorNS 
{
	[SimplInherit]
	public class TedauthorQuote : RichDocument
	{
		[SimplScalar]
		private MetadataString quote;

		[SimplComposite]
		[MmName("ted_talk")]
		private TedtalkVideo tedTalk;

		public TedauthorQuote()
		{ }

		public TedauthorQuote(MetaMetadataCompositeField mmd) : base(mmd) { }


		public MetadataString Quote
		{
			get{return quote;}
			set
			{
				if (this.quote != value)
				{
					this.quote = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}

		public TedtalkVideo TedTalk
		{
			get{return tedTalk;}
			set
			{
				if (this.tedTalk != value)
				{
					this.tedTalk = value;
					// TODO we need to implement our property change notification mechanism.
				}
			}
		}
	}
}
